# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded port 1.0 [list source [file join $dir port.1.0.tcl]]
package ifneeded portchecksum 1.0 [list source [file join $dir portchecksum.1.0.tcl]]
package ifneeded portextract 1.0 [list source [file join $dir portextract.1.0.tcl]]
package ifneeded portfetch 1.0 [list source [file join $dir portfetch.1.0.tcl]]
package ifneeded portmain 1.0 [list source [file join $dir portmain.1.0.tcl]]
package ifneeded portpatch 1.0 [list source [file join $dir portpatch.1.0.tcl]]
package ifneeded portutil 1.0 [list source [file join $dir portutil.1.0.tcl]]
