#!/usr/bin/env tclsh
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
#
# Generate a bitbucket group template Portfile given bitbucket homepage URL
#

proc usage {{channel stderr}} {
    global argv0
    puts $channel "Usage: $argv0 URL"
    puts $channel ""
    puts $channel "URL is the bitbucket homepage URL"
    puts $channel ""
    puts $channel "Example:"
    puts $channel "  $argv0 https://bitbucket.org/sshguard/sshguard"
}

proc val_or_def {val def} {
    expr {$val ne "" ? $val : $def}
}

if {$argc != 1} {
    usage
    exit 1
}

set url [lindex $argv 0]
set tmp [split $url /]

set author [val_or_def [lindex $tmp 3] author]
set project [val_or_def [lindex $tmp 3] project]
set version 1.0
set tag_prefix "";

puts "# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4"
puts "# \$Id\$"
puts ""
puts "PortSystem          1.0"

puts "PortGroup           bitbucket 1.0"
puts ""
puts "bitbucket.setup     ${author} ${project} ${version} ${tag_prefix}"

puts "categories          replaceme"
puts "platforms           darwin"

set maintainers "replaceme"

if {[info exist env(EMAIL)]} {
    set maintainers $env(EMAIL)
}

puts "maintainers         $maintainers"

puts "license             replaceme"

puts ""
puts "description         replaceme"
puts "long_description    replaceme"
puts ""

puts ""
puts "checksums           rmd160  12345 \\"
puts "                    sha256  6789a"
