#!/bin/sh
#
# $Id$
#
# Check for proper OS version for the package (meant to be used by the
# MacPorts port which replaces __DARWINVERS__ with the version of Darwin
# needed).

# error out if uname or sed can't be found
if ! which uname > /dev/null || ! which sed > /dev/null; then
    # message 16 in InstallationCheck.strings
    exit 112
fi

base_version=`uname -r | sed 's/\..*//'`
if [[ ${base_version} != __DARWINVERS__ ]]; then
   # This maps to message 17 in InstallationCheck.strings (Apple allows
   # 16-31 for custom messages); that message should also be customized
   # like this script
   exit 113
fi

if [[ -f /opt/local/etc/ports/dp_version ]]; then
   # message 18 in InstallationCheck.strings
   exit 114
fi

exit 0
