include ../../Mk/dports.mk
include ../../Mk/dports.autoconf.mk

OBJS=		CFLib.o
SHLIB_NAME=	CFLib${SHLIB_SUFFIX}
LIBS+=		-framework CoreFoundation
INSTALLDIR= ${DESTDIR}${datadir}/darwinports/Tcl/cflib1.0

include ../../Mk/dports.tea.mk
