#!/usr/bin/env port-tclsh
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

set skel_required_variables \
{ \
      PortSystem       \
      name             \
      version          \
      categories       \
      platforms        \
      license          \
      maintainers      \
      description      \
      long_description \
      master_sites     \
      checksums        \
  }

global fields

foreach var $skel_required_variables {
    set fields($var) "replaceme"
}

parray fields
