#!/usr/bin/env port-tclsh
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

set skel_required_variables \
{ \
      PortSystem       \
      name             \
      version          \
      categories       \
      platforms        \
      homepage         \
      license          \
      maintainers      \
      description      \
      long_description \
      master_sites     \
      checksums        \
  }

global fields

foreach var $skel_required_variables {
    set fields($var) "replaceme"

    # "port lint" also checks these fields' values.
    set fields(PortSystem) 1.0
    set fields(platforms) darwin
    set fields(version) 2.0
}

proc build_portfile {} {
    global fields skel_required_variables

    set modeline "# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4"
    set svn_id_tag_line "# \$Id\$"

    puts $modeline
    puts $svn_id_tag_line
    puts {}

    foreach name $skel_required_variables {
        puts [format "%-20s%s" $name $fields($name)]
        if {$name eq "PortSystem"} {
            puts {}
        }
    }
}

build_portfile
