#!/usr/bin/env port-tclsh
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

set skel_required_variables \
{ \
      PortSystem       \
      name             \
      version          \
      categories       \
      platforms        \
      homepage         \
      license          \
      maintainers      \
      description      \
      long_description \
      master_sites     \
      checksums        \
  }

global fields

foreach var $skel_required_variables {
    set fields($var) "replaceme"

    # "port lint" also checks these fields' values.
    set fields(PortSystem) 1.0
    set fields(platforms) darwin
}

proc build_portfile {} {
    global fields

    set modeline "# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4"
    set svn_id_tag_line "# \$Id\$"

    puts $modeline
    puts $svn_id_tag_line

    # NOTE: the order of iterating assoc array in this clean way is not
    # predictable, it can be resolved by using $skel_required_variables, but
    # it's fine for now since "port lint" seems to be unable to check order.
    foreach {name val} [array get fields] {
        puts [format "%-20s%s" $name $val]
    }
}

build_portfile
