# This file contains help strings for the various commands/topics in port(1)
#
# Many of these strings are place-holders right now.  Replace with genuinely
# helpful text and then delete this message.
#
# port-help.tcl
# $Id$

set porthelp(activate) "activate a port"
set porthelp(archive) "archive a port"
set porthelp(build) "build a port"
set porthelp(cat) "cat a port"
set porthelp(cd) "cd to a port"
set porthelp(checksum) "checksum a port"
set porthelp(clean) "clean a port"
set porthelp(compact) "compact a port"
set porthelp(configure) "configure a port"
set porthelp(contents) "get contents for a port"
set porthelp(deactivate) "deactivate a port"
set porthelp(dependents) "dependents a port"
set porthelp(deps) "show deps for a port"
set porthelp(destroot) "destroot a port"
set porthelp(dir) "dir a port"
set porthelp(distcheck) "distcheck a port"
set porthelp(dmg) "dmg a port"
set porthelp(dpkg) "dpkg a port"
set porthelp(echo) "echo a port"
set porthelp(ed) "ed a port"
set porthelp(edit) "edit a port"
set porthelp(exit) "exit a port"
set porthelp(extract) "extract a port"
set porthelp(fetch) "fetch a port"
set porthelp(file) "file a port"
set porthelp(gohome) "gohome a port"
set porthelp(help) "help a port"
set porthelp(info) "info a port"
set porthelp(install) "install a port"
set porthelp(installed) "installed a port"
set porthelp(lint) "lint a port"
set porthelp(list) "list a port"
set porthelp(livecheck) "livecheck a port"
set porthelp(load) "load a port"
set porthelp(location) "location a port"
set porthelp(mdmg) "mdmg a port"
set porthelp(mirror) "mirror a port"
set porthelp(mpkg) "mpkg a port"
set porthelp(outdated) "outdated a port"
set porthelp(patch) "patch a port"
set porthelp(pkg) "pkg a port"
set porthelp(platform) "platform a port"
set porthelp(provides) "provides a port"
set porthelp(quit) "quit a port"
set porthelp(rpm) "rpm a port"
set porthelp(search) "search a port"
set porthelp(selfupdate) "selfupdate a port"
set porthelp(srpm) "srpm a port"
set porthelp(submit) "submit a port"
set porthelp(sync) "sync a port"
set porthelp(test) "test a port"
set porthelp(trace) "trace a port"
set porthelp(unarchive) "unarchive a port"
set porthelp(uncompact) "uncompact a port"
set porthelp(uninstall) "uninstall a port"
set porthelp(unload) "unload a port"
set porthelp(upgrade) "upgrade a port"
set porthelp(url) "url a port"
set porthelp(usage) "usage a port"
set porthelp(variants) "variants a port"
set porthelp(version) "version a port"
