'\" t
.TH "PORT\-SYNC" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-sync \- Update the port definition files
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-qvd\fR] \fBsync\fR
.fi
.SH "DESCRIPTION"
.sp
\fBport sync\fR updates the local port definitions (the so\-called ports tree) to the latest state so you have the latest versions of ports available\&. You should normally not run \fBport sync\fR directly, but use \fBport selfupdate\fR, which updates MacPorts itself and then proceeds to do the same operation as \fBsync\fR does\&. You can, however, use \fBport sync\fR if you know that \fBselfupdate\fR does not work on your system or in your network environment, for example because your network administrator blocks outbound rsync connections and you have changed your \fBsources.conf\fR(5) to use a different method of obtaining the ports tree\&.
.sp
Running \fBsync\fR is required to get updated software with bug fixes and new features\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBWarning\fR
.ps -1
.br
.sp
When you use \fBport sync\fR, it is your responsibility to check whether new updates are available for MacPorts itself, and update them, when necessary\&. The MacPorts project will start to use new features in port definitions one week after the release of the new version, and you may run into problems when your MacPorts version has not been updated\&.
.sp .5v
.RE
.SH "GLOBAL OPTIONS"
.sp
Please see the section \fBGLOBAL OPTIONS\fR in the \fBport\fR(1) man page for a description of global port options\&.
.PP
\fB\-q\fR
.RS 4
Suppress status output, be as silent as possible\&.
.RE
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-selfupdate\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2015 The MacPorts Project
Clemens Lang <cal@macports\&.org>
.fi
.if n \{\
.RE
.\}
