'\" t
.TH "PORT\-OUTDATED" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-outdated \- List outdated ports
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-q\fR] \fBoutdated\fR
.fi
.SH "DESCRIPTION"
.sp
\fBport outdated\fR lists all ports that have newer versions available\&. For each port, it prints the name and both the old and the new version\&. \fBport outdated\fR will give you the reason why MacPorts considers a port to be outdated\&. This could be
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
due to an update, i\&.e\&. if the version number increased,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
due to a revision bump, i\&.e\&. a higher revision,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
due to an epoch increase (used in situations where the version number decreased, but the port still is newer than the previous one), or
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
due to an OS upgrade\&. MacPorts will consider ports built on a previous version of macOS outdated\&.
.RE
.sp
The ports listed in \fBport outdated\fR are the ports that will be upgraded when you run
.sp
.if n \{\
.RS 4
.\}
.nf
$> sudo port upgrade outdated
.fi
.if n \{\
.RE
.\}
.sp
i\&.e\&. those the \fIoutdated\fR pseudo\-port selector expands to, with one exception: If you have the newest version of a port installed, but deactivated in favor of an older version, \fBport outdated\fR will list it as outdated, but \fBsudo port upgrade outdated\fR will not upgrade it\&. This can be used to intentionally stay at an older version of a port, e\&.g\&. if the newer version does not work as expected\&. Note that MacPorts will still install newer versions of such ports if they are dependencies of other ports to be installed or upgraded\&.
.SH "GLOBAL OPTIONS"
.sp
Please see the section \fBGLOBAL OPTIONS\fR in the \fBport\fR(1) man page for a description of global port options\&.
.PP
\fB\-q\fR
.RS 4
Do not list the header line or the message that no ports are outdated\&.
.RE
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-upgrade\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2014 The MacPorts Project
Clemens Lang <cal@macports\&.org>
.fi
.if n \{\
.RE
.\}
