'\" t
.TH "PORT\-LOG" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-log, port-logfile \- Print contents or path of a port\*(Aqs log file
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-D\fR \fIportdir\fR] \fBlog\fR
     [\-\-level [error | warn | msg | info | debug]]
     [\-\-phase [fetch | checksum | extract | patch | configure | build | destroot]]
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.sp
.nf
\fBport\fR [\fB\-D\fR \fIportdir\fR] \fBlogfile\fR
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.SH "DESCRIPTION"
.sp
\fBport log\fR prints and optionally filters the contents of the log file for the installation of the given port\&. The file can be filtered by log message level and installation phase\&.
.sp
\fBport logfile\fR prints the path to the log file for the last installation of the given port\&. This is helpful to locate the file to attach when reporting bugs against ports in MacPorts\*(Aq issue tracker\&.
.SH "OPTIONS"
.sp
\fBport logfile\fR has no options\&. \fBport log\fR has the following options:
.PP
\fB\-\-level SEVERITY\fR
.RS 4
Hide all messages below the given severity, which is one of
.PP
error
.RS 4
for error messages
.RE
.PP
warn
.RS 4
for warnings
.RE
.PP
msg
.RS 4
for standard MacPorts output
.RE
.PP
info
.RS 4
for output shown in verbose mode
.RE
.PP
debug
.RS 4
for all output including debugging messages
.RE
.RE
.PP
\fB\-\-phase PHASE\fR
.RS 4
Only print messages that were generated in the given installation phase, where possible values for
\fBPHASE\fR
include
\fIfetch\fR,
\fIchecksum\fR,
\fIextract\fR,
\fIpatch\fR,
\fIconfigure\fR,
\fIbuild\fR, and
\fIdestroot\fR\&. Note that you can specify an arbitrary value which will be used in a regular expression to filter the log file\&.
.RE
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-install\fR(1), \fBport-clean\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2014 The MacPorts Project
Clemens Lang <cal@macports\&.org>
.fi
.if n \{\
.RE
.\}
