'\" t
.TH "PORT\-DEPENDENTS" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-dependents, port-rdependents \- List ports that depend on a given (installed) port
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-D\fR \fIportdir\fR] \fBdependents\fR
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.sp
.nf
\fBport\fR [\fB\-D\fR \fIportdir\fR] \fBrdependents\fR
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.SH "DESCRIPTION"
.sp
\fBport dependents\fR reports which ports depend upon a given (installed) port, if any\&. Note that \fBdependents\fR does not work for ports that are not installed on your system\&. It uses the database of installed ports that MacPorts keeps internally, which records the dependency relations at installation time\&. \fBport dependents\fR prints this information\&.
.sp
For this reason, \fBport dependents\fR does not work for ports that are not installed on your system\&. If you want to find out which ports depend on a port you haven\(cqt installed, you can use the \fBdepends:\fR pseudo\-portname selector:
.sp
.if n \{\
.RS 4
.\}
.nf
port echo depends:<portname>
.fi
.if n \{\
.RE
.\}
.sp
This command will, however, not cover dependencies that are only present in non\-default variants\&. For more information about pseudo\-portname selectors, see \fBport\fR(1)\&.
.sp
\fBport rdependents\fR will print a tree of installed ports that depend on the given port\&.
.sp
The dependency relations printed by \fBport dependents\fR and \fBport rdependents\fR are the same that are used to determine if a port can be safely uninstalled\&. Ports that still have dependents installed cannot be safely uninstalled without possibly breaking their dependents\&. All dependents can be removed at the same time using the \fB\-\-follow\-dependents\fR flag\&. The check can be ignored using the \fB\-f\fR flag\&. See \fBport-uninstall\fR(1) for more details\&.
.SH "DEPENDENCY RELATIONS"
.sp
Do not confuse \fIdependents\fR and \fIdependencies\fR (or, shortened, \fIdeps\fR)\&. Refer to the following example to understand the difference:
.sp
.if n \{\
.RS 4
.\}
.nf
portA \-\-> portB
.fi
.if n \{\
.RE
.\}
.sp
\fBportA\fR depends on \fBportB\fR, i\&.e\&., \fBportA\fR needs \fBportB\fR to run\&. Because of that, \fBportB\fR is a \fIdependency\fR (or \fIdep\fR) of \fBportA\fR\&. After installing \fBportA\fR, \fBportB\fR has been automatically installed\&. At this point, \fBportA\fR has become a \fIdependent\fR of \fBportB\fR\&. You can only uninstall \fBportB\fR once all of its dependents (i\&.e\&., including \fBportA\fR) have been uninstalled\&.
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-echo\fR(1), \fBport-deps\fR(1), \fBport-uninstall\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2014 The MacPorts Project
Clemens Lang <cal@macports\&.org>
.fi
.if n \{\
.RE
.\}
