'\" t
.TH "PORT\-BUMP" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-bump \- Update the outdated checksums of a Portfile
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-vd\fR] [\fB\-D\fR \fIportdir\fR] \fBbump\fR
     [\-\-patch]
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.SH "DESCRIPTION"
.sp
\fBport bump\fR updates the checksums of a Portfile if they are outdated or different than the current version\(cqs checksums\&. Additionally, the revision number will be reset\&. \fBport bump\fR is useful for maintainers to automatically bump the checksums after updating the version number of a port\&.
.SH "GLOBAL OPTIONS"
.sp
Please see the section \fBGLOBAL OPTIONS\fR in the \fBport\fR(1) man page for a description of global port options\&.
.PP
\fB\-\-patch\fR
.RS 4
Create a Portfile\&.patch file instead of directly overwriting the Portfile\&.
.RE
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-fetch\fR(1), \fBport-install\fR(1), \fBportfile\fR(7)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2019 The MacPorts Project
Satryaji Aulia <satraul@macports\&.org>
.fi
.if n \{\
.RE
.\}
