'\" t
.TH "PORT\-INFO" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-info \- Return information about the given ports\&.
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-q\fR] [\fB\-D\fR \fIportdir\fR] \fBinfo\fR
     [\-\-categories|\-\-category] [\-\-conflicts] [\-\-depends] [\-\-depends_fetch]
     [\-\-depends_extract] [\-\-depends_build] [\-\-depends_lib] [\-\-depends_run]
     [\-\-description] [\-\-epoch] [\-\-fullname] [\-\-heading] [\-\-homepage] [\-\-index]
     [\-\-license] [\-\-line] [\-\-long_description] [\-\-maintainer|\-\-maintainers]
     [\-\-name] [\-\-patchfiles] [\-\-platform|\-\-platforms] [\-\-portdir] [\-\-pretty]
     [\-\-replaced_by] [\-\-revision] [\-\-subports] [\-\-variant|\-\-variants]
     [\-\-version]
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.SH "DESCRIPTION"
.sp
\fBport info\fR prints information about the given ports\&. Specifying at least one of the options limits the output to the corresponding field\&. If no fields are specified, a useful default set consisting of name, epoch, version, revision, categories, replaced_by, variants, description, homepage, dependencies, platforms, license, and maintainers is shown\&.
.SH "OPTIONS"
.sp
The following options do not select fields for the output but change how the information is obtained or formatted:
.PP
\fB\-\-index\fR
.RS 4
Do not read the
\fIPortfile\fR, but rely solely on the port index information\&. Note that this option will prevent the information reported from reflecting the effects of any variants specified\&.
.RE
.PP
\fB\-\-line\fR
.RS 4
Print a single line for each port\&. Fields are separated by spaces\&.
.RE
.PP
\fB\-\-pretty\fR
.RS 4
Format the output in a convenient, human\-readable fashion\&. This is the default when no options are specified\&.
.RE
.sp
The rest of the options affect which fields will be given in the output:
.PP
\fB\-\-category\fR, \fB\-\-categories\fR
.RS 4
List the categories of a port\&.
.RE
.PP
\fB\-\-conflicts\fR
.RS 4
List other ports that cannot be active at the same time as the given port\&.
.RE
.PP
\fB\-\-depends\fR, \fB\-\-depends_fetch\fR, \fB\-\-depends_extract\fR, \fB\-\-depends_build\fR, \fB\-\-depends_lib\fR, \fB\-\-depends_run\fR
.RS 4
List the specified dependencies of a port\&.
\fB\-\-depends\fR
is a shorthand option for all other
\fB\-\-depends_\fR* options\&.
.RE
.PP
\fB\-\-description\fR, \fB\-\-long_description\fR
.RS 4
Print the short or long description of a port, respectively\&.
.RE
.PP
\fB\-\-epoch\fR, \fB\-\-version\fR, \fB\-\-revision\fR
.RS 4
List the components of a MacPorts version tuple, epoch, version and revision, respectively\&.
.RE
.PP
\fB\-\-fullname\fR
.RS 4
Print name and the full MacPorts version tuple, e\&.g\&., \(lqyubico\-pam @2\&.16\(rq\&.
.RE
.PP
\fB\-\-heading\fR
.RS 4
Like
\fB\-\-fullname\fR
but including the categories\&.
.RE
.PP
\fB\-\-homepage\fR
.RS 4
List the homepage of a port\&.
.RE
.PP
\fB\-\-license\fR
.RS 4
Print the license that applies to the source code of a port\&.
.RE
.PP
\fB\-\-maintainer\fR, \fB\-\-maintainers\fR
.RS 4
List the email address(es) of a port\(cqs maintainer(s)\&.
.RE
.PP
\fB\-\-name\fR
.RS 4
Print the name of a port\&.
.RE
.PP
\fB\-\-patchfiles\fR
.RS 4
List the patches that will be applied to the port, taking the current platform and selected variants into account\&. This information will not be available if
\fB\-\-index\fR
is specified\&.
.RE
.PP
\fB\-\-platform\fR, \fB\-\-platforms\fR
.RS 4
List the platforms supported by a port\&. This field exists for historical reasons only\&. In modern MacPorts, this is always
\fIdarwin\fR, i\&.e\&., macOS\&.
.RE
.PP
\fB\-\-portdir\fR
.RS 4
Print the path to a port\(cqs directory relative to the port tree root\&.
.RE
.PP
\fB\-\-replaced_by\fR
.RS 4
List the name of the port that replaces a port, if any\&.
.RE
.PP
\fB\-\-subports\fR
.RS 4
Print a list of subports defined by this port\(cqs
\fIPortfile\fR, i\&.e\&., ports that are defined in the same
\fIPortfile\fR
because they share common parts\&.
.RE
.PP
\fB\-\-variant\fR, \fB\-\-variants\fR
.RS 4
List the variants defined by a port by name\&.
.RE
.SH "GLOBAL OPTIONS"
.sp
Please see the section \fBGLOBAL OPTIONS\fR in the \fBport\fR(1) man page for a description of global port options\&.
.PP
\fB\-q\fR
.RS 4
Do not print the field description when using
\fB\-\-pretty\fR
output\&.
.RE
.SH "SEE ALSO"
.sp
\fBport\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2014\-2015 The MacPorts Project
Clemens Lang <cal@macports\&.org>
.fi
.if n \{\
.RE
.\}
