'\" t
.TH "PORT\-FETCH" "1" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
port-fetch, port-checksum, port-extract, port-patch, port-configure, port-build, port-destroot, port-test \- Run a specific phase of a port
.SH "SYNOPSIS"
.sp
.nf
\fBport\fR [\fB\-vdoy\fR] [\fB\-D\fR \fIportdir\fR] [\fBfetch\fR | \fBchecksum\fR | \fBextract\fR | \fBpatch\fR | \fBconfigure\fR | \fBbuild\fR | \fBdestroot\fR | \fBtest\fR ]
     [[\fIportname\fR | \fIpseudo\-portname\fR | \fIport\-expressions\fR | \fIport\-url\fR]]
.fi
.SH "DESCRIPTION"
.sp
These commands run a specific phase of a port\&. Depending phases will be executed automatically as needed\&.
.sp
If the \fIPortfile\fR has changed between multiple invocation, \fBport\fR will perform a clean before running the phase\&. The flag \fI\-o\fR can be used to ignore this and keep the current state of the \(lqwork\(rq dir\&.
.sp
Note that the \fBtest\fR phase is special in that it will not be run by MacPorts by default\&. When supported by the given port, the \fBtest\fR phase will run the testcases of the software\&.
.SH "GLOBAL OPTIONS"
.sp
Please see the section \fBGLOBAL OPTIONS\fR in the \fBport\fR(1) man page for a description of global port options\&.
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-install\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2010 The MacPorts Project
Rainer Mueller <raimue@macports\&.org>
.fi
.if n \{\
.RE
.\}
