'\" t
.TH "VARIANTS\&.CONF" "5" "2\&.7\&.2" "MacPorts 2\&.7\&.2" "MacPorts Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
variants.conf \- Global variant configuration file of the MacPorts system
.SH "DESCRIPTION"
.sp
\fBvariants\&.conf\fR is the configuration file used to globally select or deselect certain variants on all ports installed by MacPorts\&. Changes in this file will affect all ports that are installed after the file was changed\&.
.sp
For a description of what variants are and how they work, see \fBport-variants\fR(1)\&.
.sp
\fBvariants\&.conf\fR is read by the \fBport\fR command\&. In the file, lines beginning with \fI#\fR are comments, empty lines are ignored\&. Each line in the file is a space\- or tab\-delimited list of zero or more variants, where each variant is either explicitly enabled or disabled using a leading \fI+\fR or \fI\-\fR\&. In EBNF:
.sp
.if n \{\
.RS 4
.\}
.nf
line    = variant, { space, variant } ;
space   = \*(Aq \*(Aq | \*(Aq\et\*(Aq ;
variant = ( \*(Aq+\*(Aq | \*(Aq\-\*(Aq ), name ;
.fi
.if n \{\
.RE
.\}
.sp
where \fIname\fR is the name of the variant\&. Variants that are not provided by a port (or no port at all) are silently ignored\&.
.SH "FILES"
.sp
The path of the \fIvariants\&.conf\fR file is specified in the \fBvariants_conf\fR option of \fBmacports.conf\fR(5)\&. It defaults to \fI${prefix}/etc/macports/variants\&.conf\fR\&. There is no user\-specific \fIvariants\&.conf\fR file, but support for this can be emulated by setting \fIvariants\&.conf\fR in the user\-specific \fBmacports.conf\fR(5) file\&.
.SH "EXAMPLES"
.sp
To prefer the \fI+quartz\fR variant over \fI+x11\fR, you can add the following line to your variants\&.conf:
.sp
.if n \{\
.RS 4
.\}
.nf
\-x11 +quartz
.fi
.if n \{\
.RE
.\}
.sp
This will disable all x11 variants and enable the quartz variant, when it exists\&.
.sp
Similarly, if you want all your ports to support multiple architectures, you can enable the universal variant by default:
.sp
.if n \{\
.RS 4
.\}
.nf
+universal
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
\fBport\fR(1), \fBport-variants\fR(1)
.SH "AUTHORS"
.sp
.if n \{\
.RS 4
.\}
.nf
(C) 2015 The MacPorts Project
Clemens Lang <cal@macports\&.org>
.fi
.if n \{\
.RE
.\}
