all: build

build:
	echo "built"

install:
	echo "GSoC dummy package target:"$(DESTDIR)$(PREFIX)
	install gsoc-dummyrc $(DESTDIR)$(PREFIX)/etc
	install gsoc-dummyrc $(DESTDIR)$(PREFIX)/etc/gsoc-dummyfile-2

clean:
	


