OBJS=		darwintrace.o
SHLIB_NAME=	darwintrace${SHLIB_SUFFIX}
INSTALLDIR= ${DESTDIR}${datadir}/macports/Tcl/darwintrace1.0

test::

include ../../Mk/macports.autoconf.mk
include ../../Mk/macports.tea.mk
