#!/bin/bash

PORTPATH=$(port dir gsoc-dummy)
read _ revision <<< $(cat "$PORTPATH"/Portfile | grep revision)
echo -n "Switching gsoc-dummy from revision "
if [[ $revision = 0 ]]; then
    echo "0 to 1"
    sed -e 's,\(revision[ ]*\)0,\11,' Portfile >"$PORTPATH"/NewPortfile
else
    echo "1 to 0"
    sed -e 's,\(revision[ ]*\)1,\10,' Portfile >"$PORTPATH"/NewPortfile
fi
#mv "$PORTPATH"/NewPortfile "$PORTPATH"/Portfile